# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56ea8d795e5256470a8a70adf4a19a9a6383889a11cd996f8ca5b1d24118dda0d0cecc55409b0a75b2f4cbd708127b53ed95e45ec1bfb95a46003ff584643954

test:
  secret_key_base: 1181da92e0fd271c1ff39fbac119cafcff3834ed000cce927f3945da9e5f4067638de69d7e7886c0651ae113c19ccedac8d909c4f0d755f74ed37bd6939e6d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
